# Vexido https://github.com/vexido
# Don't remove stupid!! I'm tired of making it!

version: "3.10"
services:
  worker:
    build: .
    environment:
      TOKEN: $TOKEN
      DATABASE_URL: $DATABASE_URL
      API_ID: $API_ID
      API_HASH: $API_HASH
      OWNER_ID: $OWNER_ID
      STRING_SESSION: $STRING_SESSION
      BOT_USERNAME: $BOT_USERNAME
      BOT_ID: $BOT_ID
      OWNER_USERNAME: $OWNER_USERNAME
      SUPPORT_CHAT: $SUPPORT_CHAT
      REDIS_URL: $REDIS_URL
      MONGO_DB_URI: $MONGO_DB_URI
      IBM_WATSON_CRED_URL: $IBM_WATSON_CRED_URL
      IBM_WATSON_CRED_PASSWORD: $IBM_WATSON_CRED_PASSWORD
      EVENT_LOGS: $EVENT_LOGS
      JOIN_LOGGER: $JOIN_LOGGER
      CASH_API_KEY: $CASH_API_KEY
      TIME_API_KEY: $TIME_API_KEY
      OPENWEATHERMAP_ID: $OPENWEATHERMAP_ID
      DEV_USERS: $DEV_USERS
      ERROR_LOG: $ERROR_LOG
      ARQ_API_KEY: $ARQ_API_KEY
      SPAMWATCH_API: $SPAMWATCH_API
      STRICT_GBAN: $STRICT_GBAN
      DRAGONS: $DRAGONS
      DEMONS: $DEMONS
      TIGERS: $TIGERS
      WOLVES: $WOLVES
      ENV: $ENV
      WEBHOOK: $WEBHOOK
      PORT: $PORT
      URL: $URL
      NO_LOAD: $NO_LOAD
      BL_CHATS: $BL_CHATS
      ALLOW_EXCL: $ALLOW_EXCL
      DONATION_LINK: $DONATION_LINK
      DEL_CMDS: $DEL_CMDS
      WALL_API: $WALL_API
